# Generated by Django 4.0.3 on 2022-03-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
