# Generated by Django 4.0.3 on 2022-03-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_main_todo_context_alter_main_todo_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='guest', max_length=20)),
                ('context', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'day_todolist',
            },
        ),
        migrations.CreateModel(
            name='Sub_Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='guest', max_length=20)),
                ('context', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'sub_todolist',
            },
        ),
    ]
